application:
  name: ^project.name^
  version: ^project.version^
  hateoas: false
server:
  port: 8081
  servlet:
    context-path: /api/bff
#logging:
#  level: 
#      root: trace
#    '[com.fasterxml.jackson]': TRACE
#    '[org.springframework.data]': INFO
#    '[org.hibernate]': INFO
#    '[javax.persistence]': INFO
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui
    use-root-path: true
spring:
  jackson:
    default-property-inclusion: non-null
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: masterkey
  jpa:
    open-in-view: false
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: update
      hibernate:
        schema_update.unique_constraint_strategy: RECREATE_QUIETLY
        show_sql: true        
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
        hbm2dll:
          create_namespaces: true